### ISSUE TITLE
Failure with dev purrr

### ISSUE THREAD

**Issue by hadley** [kcf-jackson/sketch#19] opened 2022-09-29 13:36 UTC
With dev purrr, I see:

```
Error (test_compile.R:445): Test macro - top level
Error in `purrr::map_chr(res, deparse_js, deparsers = deparsers)`: ℹ In index: 1.
Caused by error in `get()`:
! object 'f' of mode 'function' was not found

Error (test_compile.R:488): Test data - top level
Error in `purrr::map_chr(res, deparse_js, deparsers = deparsers)`: ℹ In index: 1.
Caused by error in `get()`:
! object 'x' not found
```

I think this is probably due to some subtle bug around evaluation arguments but I can't tell if the bug is in purrr or sketch. Would you mind taking a look to see if you can give me any more insight?

Thanks!
Hadley

**Comment by kcf-jackson** [comment] 2022-10-03 19:54
Thanks for the notice.

I managed to reproduce the error. It seems the problem is caused by the switch of the implementation of `purrr::map_chr` from version [0.3.4](https://github.com/tidyverse/purrr/blob/b04866acedf665cb6013d3c2cc12d8587e4af7c7/R/map.R#L195)
```
map_chr <- function(.x, .f, ...) {
  .f <- as_mapper(.f, ...)
  .Call(map_impl, environment(), ".x", ".f", "character")
}
```

to the dev version [0.9000.0.9000](https://github.com/tidyverse/purrr/blob/a8e5d60172ec247b8082492d1a37226ee767dd65/R/map.R#L149)
```
map_chr <- function(.x, .f, ..., .progress = FALSE) {
  map_("character", .x, .f, ..., .progress = .progress)
}

map_ <- function(.type, .x, .f, ..., .progress = FALSE, ..error_call = caller_env()) {
  .x <- vctrs_vec_compat(.x)
  vec_assert(.x, arg = ".x", call = ..error_call)

  n <- vec_size(.x)

  names <- vec_names(.x)

  .f <- as_mapper(.f, ...)

  i <- 0L
  with_indexed_errors(
    i = i,
    error_call = ..error_call,
    .Call(map_impl, environment(), .type, .progress, n, names, i)
  )
}
```

In the new implementation, `purrr::map_chr` adds two new calls (`map_` and `with_indexed_errors`) to the call stack, and the environment returned by `sketch:::find_compile_exprs_env` is off by two nested levels. Reproducible examples are provided at the bottom.

I think the issue here is that `purrr::map_chr` used to occupy one spot in the call stack, and `find_compile_exprs_env` implicitly took advantage of that fact. I updated the implementation, and the test now passes with both 0.3.4 and the dev version of `purrr`. 

The fix is currently in the `experiment` branch, I will bundle this with the other fixes and push an update to CRAN shortly. I will close this issue when the update is accepted.


---

### Reproducible examples

#### `purrr` 0.3.4 + `sketch` 1.1.17 produce no errors
```
> # install.packages(c("purrr", "sketch"))
> packageVersion("purrr")
[1] ‘0.3.4’
> packageVersion("sketch")
[1] ‘1.1.17’
> h <- function() {
+     f <- function(x) as.character(eval(x) + 1)
+     g <- function() {
+         sketch::compile_exprs(".macro(f, 12)", 
+                               deparsers = sketch::dp("basic", "macro"))
+     }
+     g()
+ }
> h()
[1] "13"
```

Inside `sketch:::find_compile_exprs_env`, the call stack (containing 8 calls):
```
    ▆
 1. └─global h()
 2.   └─g()
 3.     └─sketch::compile_exprs(...)
 4.       └─purrr::map_chr(res, deparse_js, deparsers = deparsers)
 5.         └─sketch (local) .f(.x[[i]], ...)
 6.           └─deparser$deparse(ast, deparsers)
 7.             ├─base::get(fun_name, mode = "function", envir = find_compile_exprs_env())
 8.             └─sketch:::find_compile_exprs_env()
```

Expect: 5 nested levels from the bottom. Result: `env_ind: 5` nested levels from the bottom.


#### `purrr` 0.9000.0.9000 + `sketch` 1.1.17 produce an error
```
# remotes::install_github("tidyverse/purrr")
> packageVersion("purrr")
[1] ‘0.9000.0.9000’
> packageVersion("sketch")
[1] ‘1.1.17’
> h <- function() {
+     f <- function(x) as.character(eval(x) + 1)
+     g <- function() {
+         sketch::compile_exprs(".macro(f, 12)", 
+                               deparsers = sketch::dp("basic", "macro"))
+     }
+     g()
+ }
> h()
Error in `purrr::map_chr()`:
ℹ In index: 1.
Caused by error in `get()`:
! object 'f' of mode 'function' was not found
Run `rlang::last_error()` to see where the error occurred.
```

Inside `sketch:::find_compile_exprs_env`, the call stack (containing 11 calls; the extra calls are `map_`, `with_indexed_errors` and `base::withCallingHandlers`):
```
     ▆
  1. └─global h()
  2.   └─g()
  3.     └─sketch::compile_exprs(...)
  4.       └─purrr::map_chr(res, deparse_js, deparsers = deparsers)
  5.         └─purrr:::map_("character", .x, .f, ..., .progress = .progress)
  6.           ├─purrr:::with_indexed_errors(...)
  7.           │ └─base::withCallingHandlers(...)
  8.           └─sketch (local) .f(.x[[i]], ...)
  9.             └─deparser$deparse(ast, deparsers)
 10.               ├─base::get(fun_name, mode = "function", envir = find_compile_exprs_env())
 11.               └─sketch:::find_compile_exprs_env()
```
Expect: 6 nested levels from the bottom. Result: `env_ind: 8` nested levels from the bottom.


#### Code to produce the call stack

```
> debug(sketch:::find_compile_exprs_env)
> h()
debugging in: find_compile_exprs_env()
debug: {
    call_stack <- rlang::trace_back(globalenv())
    env_ind <- call_stack$call %>% purrr::map_lgl(~rlang::is_call(.x, 
        "compile_exprs")) %>% rev() %>% which()
    env_ind <- ifelse(purrr::is_empty(env_ind), 2, env_ind - 
        1)
    rlang::caller_env(env_ind)
}
Browse[2]> n
debug: call_stack <- rlang::trace_back(globalenv())
Browse[2]> n
debug: env_ind <- call_stack$call %>% purrr::map_lgl(~rlang::is_call(.x, 
    "compile_exprs")) %>% rev() %>% which()
Browse[2]> call_stack
```

**Comment by hadley** [comment] 2022-10-03 21:06
Thanks for looking into this! Sounds like sketch accidentally depended on an internal purrr implementation detail, and there's nothing I need to do in purrr.

**Comment by kcf-jackson** [comment] 2022-10-23 14:24
The update has been accepted on CRAN. The version is bumped up to 1.1.19. Thanks.

**Closed by kcf-jackson** 2022-10-23 14:24 UTC
